### ISSUE TITLE
Fails to build on rasberry pi b+, node v 0.12.1

### ISSUE THREAD

**Issue by YemSalat** [nebrius/raspi-llio#2]
I am getting this error when running npm install:

```
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi/node_modules/ref-struct/node_modules/ref/build'
  CXX(target) Release/obj.target/binding/src/binding.o
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory '/home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi/node_modules/ref-struct/node_modules/ref/build'

> ffi@1.2.7 install /home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi
> node-gyp rebuild

child_process: customFds option is deprecated, use stdio instead.
make: Entering directory '/home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi/build'
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
Segmentation fault
deps/libffi/ffi.target.mk:99: recipe for target 'Release/obj.target/ffi/deps/libffi/src/raw_api.o' failed
make: *** [Release/obj.target/ffi/deps/libffi/src/raw_api.o] Error 139
make: Leaving directory '/home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 4.0.7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/nodegpio/test2/node_modules/raspi-llio/node_modules/ffi
gyp ERR! node -v v0.12.1
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 4.0.7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "raspi-llio" "--save-dev"
npm ERR! node v0.12.1
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! ffi@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi@1.2.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/nodegpio/test2/npm-debug.log
```

**Comment by nebrius** [comment]
Hmm...probably a combination of node and the version of ffi that raspi-llio uses not getting along. Try it in Node 0.10 and I bet it will work.

Just so expectations are set correctly: this project is deprecated in favor of [Raspi.js](https://github.com/nebrius/raspi/). If you run into any issues, feel free to fork it and fix it yourself, but I'm not committing anything else to this project.
